#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_shell="0.0.1"
  jq -n --arg shell "$ver_shell" '{shell: $shell}'
}

version "$@"
